### ISSUE TITLE
[Troubleshooting tip] External CA 'Self-Signed Certificate in Chain' Error

### ISSUE THREAD

**Issue by timgerstel** [zowe/docs-site#1448]
### 2. Choose a title

External Certificate Authorities causing 'self-signed certificate in chain' SSL error when using API Mediation Layer (`LAUNCH_COMPONENT_GROUPS=GATEWAY,DESKTOP`)

### 3. Symptom

**Tip:** in your environment, add the variable: `NODE_DEBUG=request` for more verbose SSL debugging

After starting the app server with the gateway and desktop, a user would note either in STDOUT or in the log:

```
ZWESVUSR WARN (org.zowe.zlux.auth.safsso,apimlHandler.js:264) APIML query error: self signed certificate in certificate chain
ZWESVUSR WARN (org.zowe.zlux.auth.safsso,apimlHandler.js:338) APIML login has failed:
ZWESVUSR WARN (org.zowe.zlux.auth.safsso,apimlHandler.js:339)  Error: self signed certificate in certificate chain 
    at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)     
    at TLSSocket.emit (events.js:315:20)                    
    at TLSSocket._finishInit (_tls_wrap.js:948:8)           
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {  
  code: 'SELF_SIGNED_CERT_IN_CHAIN'                         
}  
```

### 4. Solutions

For a keystore setup with a configuration similar to:

```
EXTERNAL_CERTIFICATE=/user/external_keystore/keystore.p12
# optional - Alias of the certificate in the keystore
EXTERNAL_CERTIFICATE_ALIAS=1
# optional - Public certificates of trusted CAs - multiple certificates
# delimitad with space has to be enclosed with quotes ("cer1 cer2")
EXTERNAL_CERTIFICATE_AUTHORITIES="/user/external_keystore/root.cer /user/external_keystore/interm.cer"
```

**Solution 1: Ensure proper certificate encoding, present external CA certificates to app server**

**Important:** Attempt to view the contents of the external CA certificates, via 'cat' or a similar program. If it is unreadable within the environment, it may also be unreadable by the app server. Users may attempt to correct this issue by tagging the certificate files appropriately, i.e. binary encoded DER certificates are tagged as binary and Base64 encoded PEM certificates are tagged with their respective encoding (ISO8859-1, IBM1047, UTF8, etc).
In specific scenarios, **binary encoded DER certificates have been known to cause a self-signed error.** 

**For users with binary encoded DER certificates**, it may be necessary to download a Base64 PEM version of the CA certificates. You may also attempt to convert the DER certificates to PEM via openssl:
`openssl x509 -inform der -in certificate.cer -out certificate.pem `

- Ensure the user running the Zowe start script has read permissions for the new certificates via 'chmod' or similar commands.

Update `zowe-setup-certificates.env` to include the new certificates, and then rerun `zowe-setup-certificates.sh`:

**Before:** `EXTERNAL_CERTIFICATE_AUTHORITIES="/user/external_keystore/root.cer /user/external_keystore/interm.cer"`

**After:** `EXTERNAL_CERTIFICATE_AUTHORITIES="/user/external_keystore/root.pem /user/external_keystore/interm.pem"`

After ensuring proper encoding, add the certificates to the app-servers list of certificate authorities via the following:

- Modify $INSTANCE_DIR/instance.env to include:
`ZWED_node_https_certificateAuthorities="$KEYSTORE_DIR/local_ca/localca.cer-ebcdic","/user/external_keystore/root.pem","/user/external_keystore/interm.pem"`

**Solution 2: Switch from sso-auth plugin to zss-auth plugin (does not use certificates)**

- Modify $INSTANCE_DIR/instance.env to include:
`ZWED_dataserviceAuthentication_defaultAuthentication=zss`

- De-register sso-auth plugin via `rm $INSTANCE_DIR/workspace/app-server/plugins/org.zowe.zlux.auth.safsso.json`

- Register zss-auth plugin via `$INSTANCE_DIR/bin/install-app.sh $ROOT_DIR/components/app-server/share/zss-auth`

**Comment by 1000TurquoisePogs** [comment]
zss-auth actually doesnt use the certificates at all, so I suggest that the solutions include what you have for step 1 OR step 2, but not both.
