### ISSUE TITLE
[Troubleshooting tip] for ZWED0148E message

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1550]
### 1. Slack conversation link (if any)

Customer running into the error message `ZWED0148E`.

### 3. Symptom

```
2021-01-18 10:16:33.601 <ZWED:16847011> ZWESVUSR WARN (_zsf.bootstrap,webserver.js:156) ZWED0148E - Exception thrown when reading SAF keyring, e= TypeError: R_datalib call failed: function code: 01, SAF rc: 8, RACF rc: 8, RACF rsn: 44
    at Object.getPemEncodedData (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/keyring_js/index.js:21:26)
    at /software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/lib/webserver.js:140:38
    at Array.forEach (<anonymous>)
    at loadPem (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/lib/webserver.js:125:9)
    at readTlsOptionsFromConfig (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/lib/webserver.js:198:23)
    at WebServer.setConfig (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/lib/webserver.js:312:7)
    at Server.<anonymous> (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/lib/index.js:185:20)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/software/zowev15/1.15.0/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)
```
### 4. Solution
 
https://github.com/zowe/zowe-install-packaging/issues/1664 message ZWED0148E indicates that Zowe's local CA does not exist in the keyring. It has default name localca. The Zowe desktop hardcodes the localca certificate in its config scripts and expects that the localca always exists.

The customer is using their own trusted CA certificate ( ZOWE_SPLEX) in the keyring (ZOWEKEYRING_SPLEX), the error message is written in Zowe log and it may be confusing. It doesn't affect functionality of Zowe Desktop.

Adding ZWED_node_https_certificateAuthorities="safkeyring:////ZWESVUSR/ZOWEKEYRING_SPLEX&External CA Name", in instance.env file will resolve the issue of ZWED0148E.

**Comment by 1000TurquoisePogs** [comment]
The proposed solution stopped being totally correct in v1.17.0
148E still exists but for different reasons.


ZWED0148E indicates that a CA, key, or cert does not exist in the zowe keyring. 
In the same log, there will be a message ZWED5018I which shows a section explaining the current https configuration, such as 
```
    "https": {
      "ipAddresses": [
        "0.0.0.0"
      ],
      "port": 8544,
      "keys": [
        "safkeyring:////ZWESVUSR/ring&Label A"
      ],
      "certificates": [
        "safkeyring:////ZWESVUSR/ring&Label A"
      ],
      "certificateAuthorities": [
        "safkeyring:////ZWESVUSR/ring&Label B",
        "safkeyring:////ZWESVUSR/ring&Label B"
      ]
    },
```

The label names must exactly match what is shown in TSO when looking up the keyring owned by the zowe user.
If there are differences in spaces, capitalization, or any other differences then this will cause ZWED0148E.

In that case, the solution is to correct zowe configuration to make the match.

It is also sometimes the case that customers use external certificates in a way that they dont have a "LOCAL CA" because they are using external keystore objects. In that case, "LOCAL CA" and "EXTERNAL CA" should be able to have the same value, and therefore look like its being loaded twice, but should do so without error.
